language: python
sudo: false
python:
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install .
script:
    - python examples/advectiondiffusion1D/gaussian_step_noplot.py
